baseURL = "https://fredericogago.github.io/"
languageCode = "en-us"
title = "Frederico Gago – Tech Blog"
theme = "PaperMod"
publishDir = "docs"
enableRobotsTXT = true

[params]
  env = "production"
  description = "Technical blog on Python 3.13, Clean Architecture, and modern software engineering practices."
  keywords = ["Python", "Clean Architecture", "Type Hints", "SOLID", "FastAPI", "Portfólio"]
  author = "Frederico Gago"

  ShowReadingTime = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  defaultTheme = "auto"
  mainSections = ["posts"]
  ShowMenu = true

  socialIcons = [
    { name = "github", url = "https://github.com/fredericogago" },
    { name = "linkedin", url = "https://www.linkedin.com/in/frederico-gago-5849281aa" }
  ]

  [params.profileMode]
    enabled = true
    name = "Frederico Gago"
    subtitle = "Software Developer focused on Clean Architecture and Python."
    imageUrl = "images/profile.jpg"
    imageTitle = "Profile picture"

    [[params.profileMode.buttons]]
      name = "Blog"
      url = "/posts"

    [[params.profileMode.buttons]]
      name = "GitHub"
      url = "https://github.com/fredericogago"

[menu]
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 1

  [[menu.main]]
    identifier = "portfolio"
    name = "Portfolio"
    url = "/portfolio/"
    weight = 2

  [[menu.main]]
    identifier = "contact"
    name = "Contact"
    url = "/contact/"
    weight = 3

  [[menu.main]]
    identifier = "blog"
    name = "Blog"
    url = "/posts/"
    weight = 4

[outputs]
  home = ["HTML", "RSS", "JSON"]

[markup]
  [markup.highlight]
    noClasses = false
